### ISSUE TITLE
Unsupported Regex

### ISSUE THREAD

**Issue by fubar-coder** [LanguageDev/Yoakke#145]
**Describe the bug**

I'm unable to use the following regular expression as token:

`([^)]*\)[^\]])*[^)]*`

The build fails with the following error:

```
TokenType.cs(45,5): Error YKLEXERGEN006 : Failed to parse regular expression invalid escape \] in grouping (position 10)
```

**Which libraries does it affect?**
Which Yoakke modules are you using that causes this problem.

Maybe either `Yoakke.SynKit.Lexer.Generator` or `Yoakke.SynKit.Lexer`.

**To Reproduce**
1. Create a TokenType
2. Add a RegEx entry to the TokenType like this `[Regex(@"([^)]*\)[^\]])*[^)]*")] Test,`
3. Add the lexer
4. Try to build

**Expected behavior**

The regular expression seems to be find when using online Regex testers, so it should (IMHO) be usable.

**Environment (please complete the following information):**
 - OS: Windows 11
 - .NET version: .NET 6
 - Version 2022.3.14-2.38.26-nightly
 - IDE: Rider 2021.3.3

**Additional context**

**Comment by LPeter1997** [comment]
Sorry for the late reply!

I've confirmed, this is a bug. Sadly my initial Regex grammar and parser is not really sophisticated. Yoakke uses a custom regex parser because they are converted to DFAs underneath to be as fast as possible. I'll try to start reworking that part, but I'd really like to see some industrial-grade regex grammar as a reference. The one I'm using right now is made up by me, but probably doesn't cover nearly enough of the cases it should.
