### ISSUE TITLE
Make it possible to define generic visitors

### ISSUE THREAD

**Issue by LPeter1997** [LanguageDev/Yoakke#71]
**Is your feature request related to a problem? Please describe.**
There is a high possibility that visitors with the same "shape" will be reused a lot. This can partially be solved by #68 , but I think it'd still be nice to be able to generate generic visitors.

**Describe the solution you'd like**
There should be a possibility to reference to the defined generic parameters. The problem is that attributes can't reference the generic parameters declared inside the classes:
```cs
[SyntaxTreeVisitor(typeof(Node), ReturnType = typeof(TValue))] // error CS0416: 'TValue': an attribute argument cannot use type parameters
public abstract partial class MyVisitorBase<TValue> { /* ... */ }
```

**Describe alternatives you've considered**
A very simple solution could be to introduce special marker types to reference the first, second, third, ... (8 should be plenty) generic parameters, like so:
```cs
[SyntaxTreeVisitor(typeof(Node), ReturnType = typeof(GenericParam.P1))] // P1 will reference TValue
public abstract partial class MyVisitorBase<TValue> { /* ... */ }
```

Another simple solution is referencing them by name in a separate property on the attribute. The advantage here is that `nameof` works from the outside:
```cs
[SyntaxTreeVisitor(typeof(Node), GenericReturnType = nameof(TValue))]
public abstract partial class MyVisitorBase<TValue> { /* ... */ }
```
This latter case would only complicate in the fact that `ReturnType` and `GenericReturnType` have to be orthogonally specified.

**Comment by skneko** [comment]
First, I think this is a good idea, and something I've thought too.

Regarding the alternatives, I don't really like the first alternative because it is limited to an arbitrary number (it's very likely 8 will be enough for most cases, but why go for a limit when you can avoid?) and also because it doesn't use the generic type parameter name. Using position (P1, P2...) could result in hard to debug errors if the order of the generic type arguments changes later, and it also makes reading a bit more obscure. 

On the other hand, the second alternative completely removes the arbitrary number limit and directly references the generic type argument by name. Even if the use of `nameof` is required, it is not completely counterintuitive as many other arguments already require the user to know `typeof`, and the typecheck of CSC will also disallow people from wrongly passing a type instead of a string. Furthermore, there exist lints in Microsoft analyzers (I've seen them before) that would suggest the user to use `nameof` if they try to write the name of a type verbatim as a string literal.
